import os
import json
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

_client = Groq(api_key=os.environ["GROQ_API_KEY"])

SYSTEM_PROMPT = """You are an expert linguistic forensics system. Analyze the provided text across three semantic dimensions to determine if it was generated by an LLM or written by a human.

Do NOT evaluate formatting, word count, or sentence length — only meaning, transitions, and tone.

Score each dimension from 0.0 (strongly AI) to 1.0 (strongly human):

1. Transitional Signposting: AI relies on formulaic bridges ("Furthermore," "In conclusion," "It is important to note"). Human text transitions via narrative context. Score low if formulaic, high if organic.

2. Semantic Progression: AI restates the same premise in shifted vocabulary to fill space. Human text builds or develops the idea. Score low if you see redundant loops, high if ideas advance.

3. Tone Authenticity: AI is ultra-polished, hyper-neutral, risk-averse. Human writing drifts stylistically — colloquial, idiosyncratic, sometimes imperfect. Score low if hollow/sterile, high if voice is distinct.

Calibration anchors for the FINAL confidence score:
- 0.9–1.0: Unmistakably one or the other. Clear, repeated, consistent signals across all dimensions.
- 0.7–0.89: Strong lean. Most signals agree but one dimension is ambiguous.
- 0.5–0.69: Moderate lean. Signals are mixed or the text is short/neutral.
- 0.3–0.49: Weak lean. More uncertain than certain.
- 0.0–0.29: Near-guesswork. Text is genuinely ambiguous.

Reserve scores above 0.8 only for text that is unambiguously one category.

Respond with a JSON object only — no explanation, no markdown:
{
  "dimension_scores": {"transitions": <float>, "progression": <float>, "tone": <float>},
  "attribution": "likely_ai" or "likely_human",
  "confidence": <float>
}"""


def llm_signal(text: str) -> dict:
    """
    Signal 1: LLM-based classification via Groq.
    Returns {"attribution": str, "confidence": float}
    """
    response = _client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0.0,
    )

    raw = response.choices[0].message.content.strip()
    result = json.loads(raw)

    attribution = result["attribution"]
    confidence = float(result["confidence"])

    if attribution not in ("likely_ai", "likely_human"):
        return {"attribution": "likely_human", "confidence": 0.0}
    confidence = max(0.0, min(1.0, confidence))

    return {"attribution": attribution, "confidence": confidence}